config/routes.rb
Spree::Core::Engine.routes.draw do
  resources :gift_cards, only: [:new, :create] do
    member do
      get :redeem
    end
  end

  resources :orders, only: [] do
    patch :apply_gift_card
  end

  namespace :admin do
    resources :gift_cards
  end
end

app/models/concerns/spree/order/gift_card.rb
module Spree
  class Order
    module GiftCard
      extend ActiveSupport::Concern

      def add_gift_card_payments(gift_card)
        payments.gift_cards.checkout.map(&:invalidate!)

        if gift_card.present?
          payment_method = Spree::PaymentMethod::GiftCard.available.first
          raise "Gift Card payment method could not be found" unless payment_method

          amount_to_take = gift_card_amount(gift_card, outstanding_balance_after_applied_store_credit)
          create_gift_card_payment(payment_method, gift_card, amount_to_take)
        end
      end

      def remove_gift_card_payments
        payments.checkout.gift_cards.map(&:invalidate!) unless completed?
      end

      def total_applied_gift_card
        payments.gift_cards.valid.sum(:amount)
      end

      def using_gift_card?
        total_applied_gift_card > 0
      end

      def display_total_applied_gift_card
        Spree::Money.new(-total_applied_gift_card, currency: currency)
      end

      included do
        def order_total_after_store_credit_with_gift_card
          order_total_after_store_credit_without_gift_card - total_applied_gift_card
        end
        alias_method :order_total_after_store_credit_without_gift_card, :order_total_after_store_credit
        alias_method :order_total_after_store_credit, :order_total_after_store_credit_with_gift_card
      end

      def add_store_credit_payments
        payments.store_credits.where(state: 'checkout').map(&:invalidate!)

        remaining_total = outstanding_balance - total_applied_gift_card

        if user && user.store_credits.any?
          payment_method = Spree::PaymentMethod::StoreCredit.available.first
          raise "Store credit payment method could not be found" unless payment_method

          user.store_credits.order_by_priority.each do |credit|
            break if remaining_total.zero?
            next if credit.amount_remaining.zero?

            amount_to_take = store_credit_amount(credit, remaining_total)
            create_store_credit_payment(payment_method, credit, amount_to_take)
            remaining_total -= amount_to_take
          end
        end
      end

      def outstanding_balance_after_applied_store_credit
        outstanding_balance - total_applied_store_credit
      end

      private

        def create_gift_card_payment(payment_method, gift_card, amount)
          payments.create!(
            source: gift_card,
            payment_method: payment_method,
            amount: amount,
            state: 'checkout',
            response_code: gift_card.generate_authorization_code
          )
        end

        def gift_card_amount(gift_card, total)
          [gift_card.amount_remaining, total].min
        end
    end
  end
end

app/models/spree/gift_card.rb
module Spree
  class GiftCard < ActiveRecord::Base
    include CalculatedAdjustments

    UNACTIVATABLE_ORDER_STATES = ["complete", "awaiting_return", "returned"]
    AUTHORIZE_ACTION = 'authorize'
    CAPTURE_ACTION = 'capture'
    VOID_ACTION = 'void'
    CREDIT_ACTION = 'credit'

    belongs_to :variant
    belongs_to :line_item, required: false

    has_many :transactions, class_name: 'Spree::GiftCardTransaction'

    validates :current_value, :name, :original_value, :code, :email, presence: true

    with_options allow_blank: true do
      validates :code, uniqueness: { case_sensitive: false }
      validates :current_value, numericality: { greater_than_or_equal_to: 0 }
      validates :email, length: { maximum: 254, allow_blank: false }, email: { allow_blank: false }
    end

    validate :amount_remaining_is_positive, if: :current_value

    before_validation :generate_code, on: :create
    before_validation :set_values, on: :create

    def safely_redeem(user)
      if able_to_redeem?(user)
        redeem(user)
      elsif amount_remaining.to_f > 0.0
        errors.add(:base, Spree.t('errors.gift_card.unauthorized'))
        false
      else
        errors.add(:base, Spree.t('errors.gift_card.already_redeemed'))
        false
      end
    end

    def amount_remaining
      current_value - authorized_amount
    end

    def authorize(amount, options = {})
      authorization_code = options[:action_authorization_code]
      if authorization_code
        if transactions.find_by(action: AUTHORIZE_ACTION, authorization_code: authorization_code)
          return true
        else
          errors.add(:base, Spree.t('gift_card_payment_method.unable_to_capture', auth_code: authorization_code))
          return false
        end
      else
        authorization_code = generate_authorization_code
      end

      if valid_authorization?(amount)
        transaction = self.transactions.build(action: AUTHORIZE_ACTION, amount: amount, authorization_code: authorization_code)
        transaction.order = Spree::Order.find_by(number: options[:order_number]) if options[:order_number]
        self.authorized_amount = self.authorized_amount + amount
        self.save!
        authorization_code
      else
        false
      end
    end

    def valid_authorization?(amount)
      if amount_remaining.to_d < amount.to_d
        errors.add(:base, Spree.t('gift_card_payment_method.insufficient_funds'))
        false
      else
        true
      end
    end

    def capture(amount, authorization_code, options = {})
      return false unless authorize(amount, action_authorization_code: authorization_code)

      if amount <= authorized_amount
        transaction = self.transactions.build(action: CAPTURE_ACTION, amount: amount, authorization_code: authorization_code)
        transaction.order = Spree::Order.find_by(number: options[:order_number]) if options[:order_number]
        self.authorized_amount = self.authorized_amount - amount
        self.current_value = self.current_value - amount
        self.save!
        authorization_code
      else
        errors.add(:base, Spree.t('gift_card_payment_method.insufficient_authorized_amount'))
        false
      end
    end

    def void(authorization_code, options = {})
      if auth_transaction = transactions.find_by(action: AUTHORIZE_ACTION, authorization_code: authorization_code)
        amount = auth_transaction.amount
        transaction = self.transactions.build(action: VOID_ACTION, amount: amount, authorization_code: authorization_code)
        transaction.order = Spree::Order.find_by(number: options[:order_number]) if options[:order_number]
        self.authorized_amount = self.authorized_amount - amount
        self.save!
        true
      else
        errors.add(:base, Spree.t('gift_card_payment_method.unable_to_void', auth_code: authorization_code))
        false
      end
    end

    def credit(amount, authorization_code, options = {})
      capture_transaction = transactions.find_by(action: CAPTURE_ACTION, authorization_code: authorization_code)
      if capture_transaction && amount <= capture_transaction.amount
        transaction = self.transactions.build(action: CREDIT_ACTION, amount: amount, authorization_code: authorization_code)
        transaction.order = Spree::Order.find_by(number: options[:order_number]) if options[:order_number]
        self.current_value = self.current_value + amount
        self.save!
        true
      else
        errors.add(:base, Spree.t('gift_card_payment_method.unable_to_credit', auth_code: authorization_code))
        false
      end
    end

    # Calculate the amount to be used when creating an adjustment
    def compute_amount(calculable)
      self.calculator.compute(calculable, self)
    end

    def debit(amount, order = nil)
      raise 'Cannot debit gift card by amount greater than current value.' if (amount_remaining - amount.to_f.abs) < 0
      transaction = self.transactions.build
      transaction.amount = amount
      transaction.order = order if order
      self.current_value = self.current_value - amount.abs
      self.save
    end

    def price
      self.line_item ? self.line_item.price * self.line_item.quantity : self.variant.price
    end

    def order_activatable?(order)
      order &&
        created_at < order.created_at &&
        current_value > 0 &&
        !UNACTIVATABLE_ORDER_STATES.include?(order.state)
    end

    def calculator
      @calculator ||= Spree::Calculator::GiftCardCalculator.new
    end

    def actions
      [:capture, :void]
    end

    def generate_authorization_code
      "#{id}-GC-#{Time.now.utc.strftime('%Y%m%d%H%M%S%6N')}"
    end

    def can_void?(payment)
      payment.pending?
    end

    def can_capture?(payment)
      ['checkout', 'pending'].include?(payment.state)
    end

    private

    def redeem(user)
      begin
        transaction do
          previous_current_value = amount_remaining
          debit(amount_remaining)
          build_store_credit(user, previous_current_value).save!
        end
      rescue Exception => e
        self.errors[:base] = 'There some issue while redeeming the gift card.'
        false
      end
    end

    def build_store_credit(user, previous_current_value)
      user.store_credits.build(
        amount: previous_current_value,
        category: Spree::StoreCreditCategory.gift_card.last,
        memo: "Gift Card - #{ variant.product.name } received from #{ recieved_from }",
        created_by: user,
        action_originator: user,
        currency: Spree::Config[:currency]
      )
    end

    def recieved_from
      line_item.order.email
    end

    def generate_code
      until self.code.present? && self.class.where(code: self.code).count == 0
        self.code = Digest::SHA1.hexdigest([Time.now, rand].join)
      end
    end

    def set_values
      self.current_value ||= self.variant.try(:price)
      self.original_value ||= self.variant.try(:price)
    end

    def amount_remaining_is_positive
      unless amount_remaining >= 0.0
        errors.add(:authorized_amount, Spree.t('errors.gift_card.greater_than_current_value'))
      end
    end

    def able_to_redeem?(user)
      Spree::Config.allow_gift_card_redeem && user && user.email == email && amount_remaining.to_f > 0.0 && line_item.order.completed?
    end

  end
end

app/controllers/spree/admin/gift_cards_controller.rb
module Spree
  module Admin
    class GiftCardsController < Spree::Admin::ResourceController
      before_action :find_gift_card_variants, except: :destroy

      def create
        @object.assign_attributes(gift_card_params)
        if @object.save
          flash[:success] = Spree.t(:successfully_created_gift_card)
          redirect_to admin_gift_cards_path
        else
          render :new
        end
      end

      private
      def collection
        super.order(created_at: :desc).page(params[:page]).per(Spree::Config[:admin_orders_per_page])
      end

      def find_gift_card_variants
        gift_card_product_ids = Product.not_deleted.where(is_gift_card: true).pluck(:id)
        @gift_card_variants = Variant.joins(:prices).where(["amount > 0 AND product_id IN (?)", gift_card_product_ids]).order("amount")
      end

      def gift_card_params
        params.require(:gift_card).permit(:email, :name, :note, :value, :variant_id, :enabled)
      end

    end
  end
end

app/controllers/spree/gift_cards_controller.rb
module Spree
  class GiftCardsController < Spree::StoreController

    before_action :load_master_variant, only: :new
    before_action :load_gift_card, only: :redeem

    def redeem
      if @gift_card.safely_redeem(spree_current_user)
        redirect_to redirect_after_redeem, flash: { success: Spree.t(:gift_card_redeemed) }
      else
        redirect_to root_path, flash: { error: @gift_card.errors.full_messages.to_sentence }
      end
    end

    def new
      find_gift_card_variants
      @gift_card = GiftCard.new
    end

    def create
      begin
        # Wrap the transaction script in a transaction so it is an atomic operation
        Spree::GiftCard.transaction do
          @gift_card = GiftCard.new(gift_card_params)
          @gift_card.save!
          # Create line item
          line_item = LineItem.new(quantity: 1)
          line_item.gift_card = @gift_card
          line_item.variant = @gift_card.variant
          line_item.price = @gift_card.variant.price
          # Add to order
          order = current_order(create_order_if_necessary: true)
          order.line_items << line_item
          line_item.order = order
          order.update_totals
          order.updater.update_item_count
          order.save!
          # Save gift card
          @gift_card.line_item = line_item
          @gift_card.save!
        end
        redirect_to cart_path
      rescue ActiveRecord::RecordInvalid
        find_gift_card_variants
        render :new
      end
    end

    private

    def redirect_after_redeem
      root_path
    end

    def load_gift_card
      @gift_card = Spree::GiftCard.where(code: params[:id]).last
      unless @gift_card
        redirect_to root_path, flash: { error: Spree.t(:gift_code_not_found) }
      end
    end

    def find_gift_card_variants
      gift_card_product_ids = Product.not_deleted.where(is_gift_card: true).pluck(:id)
      @gift_card_variants = Variant.joins(:prices).where(["amount > 0 AND product_id IN (?) AND currency = (?)", gift_card_product_ids, Spree::Config.currency]).order("amount")
    end

    def gift_card_params
      params.require(:gift_card).permit(:email, :name, :note, :variant_id)
    end

    def load_master_variant
      @master_variant = Spree::Product.find_by(slug: params[:product_id]).try(:master)
    end

  end
end

app/helpers/spree/admin/gift_cards_helper.rb
module Spree::Admin::GiftCardsHelper
  def variants_values(gift_card_variants)
    gift_card_variants.map { |variant| [variant.display_price, variant.id] }
  end
end

app/helpers/spree/gift_cards_helper.rb
module Spree::GiftCardsHelper
  def variants_values(gift_card_variants)
    gift_card_variants.map { |variant| ["#{ variant.display_price.to_s } - #{ variant.product.name }", variant.id] }
  end
end

app/views/spree/admin/gift_cards/_form.html.erb
<div data-hook="admin_gift_card_form_fields" class="row clearfix">
  <div class="col-md-5">
    <%= f.field_container :email do %>
      <%= f.label :email %> <span class="required">*</span><br/>
      <%= f.text_field :email, class: 'form-control' %>
      <%= f.error_message_on :email %>
    <% end %>
  </div>
  <div class="col-md-5">
    <%= f.field_container :name do %>
      <%= f.label :name %> <span class="required">*</span><br/>
      <%= f.text_field :name, class: 'form-control' %>
      <%= f.error_message_on :name %>
    <% end %>
  </div>

  <div class="col-md-5">
    <%= f.field_container :note do %>
      <%= f.label :note %>
      <%= f.text_area :note, rows: 3, class: 'form-control' %>
      <%= f.error_message_on :note %>
    <% end %>
  </div>

  <div class="col-md-5">
    <%= f.field_container :variant_id do %>
      <%= f.label :variant_id, Spree.t(:value) %> <span class="required">*</span><br/>
      <%= f.select :variant_id, variants_values(@gift_card_variants), {}, class: 'form-control' %>
    <% end %>
  </div>

  <div class="col-md-5">
    <%= f.field_container :enabled do %>
      <%= f.label :enabled %>
      <%= f.check_box :enabled %>
    <% end %>
  </div>

</div>

app/views/spree/admin/gift_cards/edit.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:editing_gift_card) %>
<% end %>

<% content_for :page_actions do %>
  <li>
    <%= button_link_to Spree.t(:back_to_gift_cards_list), spree.admin_gift_cards_path, icon: 'icon-arrow-left' %>
  </li>
<% end %>

<%= render partial: 'spree/shared/error_messages', locals: { target: @gift_card } %>

<%= form_for [:admin, @gift_card] do |f| %>
  <fieldset class="no-border-top">
    <%= render partial: 'form', locals: { f: f } %>
    <%= render partial: 'spree/admin/shared/edit_resource_links' %>
  </fieldset>
<% end %>

<h2><%= Spree.t(:transactions) %><h2>
<ul>
  <% @gift_card.transactions.authorize.each do |transaction| %>
  <li><%= link_to "#{transaction.order.number}:" , edit_admin_order_path(transaction.order) %> <%= number_to_currency transaction.amount %></li>
  <% end %>
</ul>

app/views/spree/admin/gift_cards/index.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:gift_cards) %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:new_gift_card), new_object_url, icon: 'plus', class: 'btn btn-success' %>
<% end %>

<% content_for :table_filter_title do %>
  <h2>Testing</h2>
<% end %>

<table class="index table table-hover">
  <thead>
    <tr>
      <th><%= Spree.t(:code) %></th>
      <th><%= Spree.t(:original_value) %></th>
      <th><%= Spree.t(:current_value) %></th>
      <th><%= Spree.t(:email) %></th>
      <th><%= Spree.t(:name) %></th>
      <th><%= Spree.t(:note) %></th>
      <th class="actions" width="100"></th>
    </tr>
  </thead>
  <tbody>
    <% @gift_cards.each do |card| %>
      <tr id="<%= spree_dom_id card %>">
        <td><%= card.code %></td>
        <td><%= number_to_currency card.original_value %></td>
        <td><%= number_to_currency card.current_value %></td>
        <td><%= card.email %></td>
        <td><%= card.name %></td>
        <td><%= card.note %></td>
        <td class="actions">
          <%= link_to_edit card, no_text: true if can?(:edit, card) %>
          &nbsp;
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @gift_cards %>

app/views/spree/admin/gift_cards/new.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:new_gift_card) %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:back_to_gift_cards_list), spree.admin_gift_cards_path, icon: 'arrow-left', class: 'btn btn-primary' %>
<% end %>

<%= render partial: 'spree/shared/error_messages', locals: { target: @gift_card } %>

<%= form_for [:admin, @gift_card] do |f| %>
  <fieldset class="no-border-top">
    <%= render partial: 'form', locals: { f: f } %>
    <%= render partial: 'spree/admin/shared/new_resource_links' %>
  </fieldset>
<% end %>